name: Rebase Main onto Production

on:
  push:
    branches:
      - main

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout production branch
        run: git checkout production

      - name: Rebase main onto production
        run: |
          # Rebase the production branch with the latest changes from main
          git rebase origin/main

      - name: Push changes to production branch
        run: git push origin production --force-with-lease
