name: Rebase Main onto Production

on:
  push:
    branches:
      - main

permissions:
  contents: write # Repositories contents access (for push)
  pull-requests: write # Optional if dealing with PRs

jobs:
  cherry-pick:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout production branch
        run: |
          git fetch origin production
          git checkout production

      - name: Cherry-pick the latest commit from main
        run: |
          # Cherry-pick을 위한 최신 커밋 ID 가져오기
          COMMIT_HASH=$(git log origin/main -n 1 --pretty=format:"%H")
          git cherry-pick $COMMIT_HASH

      - name: Push changes to production
        run: |
          git push origin production
